### ISSUE TITLE
Provide BEACON file

### ISSUE THREAD

**Issue by lehkost** [dracor-org/einakter#122]
Building on the discussion in #51, we should discuss the best way to provide a BEACON file for our ~~data (works and authors)~~ plays.

For starters, which authority should we rely on, GND, or Wikidata, or both?

**Comment by cmil** [comment]
For a BEACON file for authors wouldn't we first have to implement author pages?

**Comment by lehkost** [comment]
Very true. I forgot that we didn't even do this for main DraCor yet. 😬 So it would be works only for now…

**Comment by lehkost** [comment]
Should we change the BEACON pointers from slugs to IDs, now that we have them?
