### ISSUE TITLE
Allow multiple authors per play

### ISSUE THREAD

**Issue by lehkost** [dracor-org/einakter#14]
The necessity occurred with Meyer's and Schröder's co-authored translation ["Die Übereilung"](https://einakter.dracor.org/meyer-schroeder-die-uebereilung) (1790). This extension of our data model should not have format-breaking consequences for neither the YAML nor the JSON format of our data.

**Comment by cmil** [comment]
This change will not be backwards compatible because we need to change the `author` object to an `authors` array.
