### ISSUE TITLE
Add author columns to CSV output

### ISSUE THREAD

**Issue by lehkost** [dracor-org/einakter#161]
We offer our metadata in 2 formats:
- https://einakter.dracor.org/data.json
- https://einakter.dracor.org/data.csv

Because of the constraints of the CSV format, these two files do not carry the same information at this point. This is not a general problem, since e.g. character lists are not well-placed in a CSV file, I'd argue.

However, we could start using lists in CSV cells where it makes sense. I think we should introduce author fields in the CSV file (just like in JSON) and in the case of double authorship, we should use lists to fill the cells, for example regarding [this play](https://einakter.dracor.org/id/ein001574):

- column head: **authorName**
  - value: ["Meyer, Friedrich Ludwig Wilhelm", "Schröder, Friedrich Ludwig"]
- column head: **authorPseudonym** (if applicable)
  - […]
- column head: **authorWikidataID**
  - value: "[Q1460909, Q213877]"

The same we could do with keywords. Right now we separate them by line breaks.

What do you think?

**Comment by cmil** [comment]
A few questions:

1. Do I understand correctly, that you want to write the lists in JSON syntax with square brackets and quotation marks into the CSV cells?
2. Are there applications that support that format in CSV?
3. Wouldn't it be easier to use if we use another separator, say a semicolon, for multiple value in a cell?
4. Don't we already do something like this in the DraCor API metadata CSV?

**Comment by lehkost** [comment]
1. Not necessarily in JSON syntax, any solution that makes sense would work for me.
2. Occasionally spotted in the wild, but see 1., I have no strong preference.
3. Definitely, yes. Will be easier to parse, too. Instead of the semicolon, maybe use ```|``` instead?
4. Yes, as far as I can see we use this 'method' in the ```maxDegreeIds``` column if there is more than 1 character with the same (maximum) degree. We decided to use the ```|``` sign there, so probably could stick to it here. (However, in the main DraCor CSV metadata outpout, in case of multiple authors, we only name the first author and then put a number in the ```numOfCoAuthors``` column if there is more than one. I think the idea was to avoid having lists in CSV cells as much as possible.)

**Comment by lehkost** [comment]
Strong support for the ```|``` approach in case of multiple authorship (but shouldn't be more than a handful of cases).

**Comment by cmil** [comment]
I would be fine using `|`. But can we make sure this comes at least close to something like a best practice. I mean, this is certainly a problems others had before us, and I would suggest to make sure we use something that is recognised as a solution as widely as possible.
