### ISSUE TITLE
If only a premiere date is provided, "Year (normalized)" is not calculated.

### ISSUE THREAD

**Issue by lehkost** [dracor-org/einakter#17]
Seems to happen only when an exact premiere date is provided, like here: https://einakter.dracor.org/anonym-le-babillard-der-schwaetzer

While we're at it, in case only a month is provided, the date seems to be auto-completed to the first day of the month. If premiere date can only be narrowed down to the month, like "1815-01", it should show like "1.1815" or maybe "xx.1.1815" in the frontend. So far, there is only one example for this phenomenon: https://einakter.dracor.org/buerger-die-antike-statue-aus-florenz

**Comment by cmil** [comment]
The partial dates like are now rendered as `monthname year`, e.g. "1805-01" becomes "January 1805".
