### ISSUE TITLE
Attach JSON and CSV datasets to GitHub releases

### ISSUE THREAD

**Issue by v-ji** [dracor-org/einakter#171]
Seeing as the CSV and JSON dataset outputs are static, we could think about attaching them as assets to each GitHub release.

This would aid in reproducibility, as there is currently no way to reference or fetch the JSON/CSV representation of the dataset of a particular version. The stable URL assigned to the release assets by GitHub could for example be used by executable papers to ensure consistent results.

It would probably make sense to generate and attach the assets automatically via Actions.

**Alternatives considered**  
Git checkout: While it is possible to check out any commit or tag and access the raw `data.yaml`, this method lacks year normalisation and other variables.

**Comment by cmil** [comment]
I implemented a workflow that attaches the JSON and CSV files to the release. See https://github.com/dracor-org/einakter/releases/tag/v1.5.0-beta.1 as an example.
