### ISSUE TITLE
Align heads of column with mainstream DraCor wording

### ISSUE THREAD

**Issue by lehkost** [dracor-org/einakter#173]
For the API 1.0 release of DraCor, we unified the wording for names/properties. To avoid misunderstandings, the Einakter table we are spitting out should be aligned to this wording:
* normalizedYear → yearNormalized
* created → yearWritten
* printed → yearPrinted
* premiered → datePremiered
* *has to be added:* yearPremiered

I would also propose to shorten "number" to "num" here:
* numberOfScenes → numOfScenes
* numberOfCharacters → numOfCharacters

In mainstream DraCor, these properties are called numOfSegments and numOfSpeakers, in the Einakter database we should keep numOfScenes and numOfCharacters, as they are different information (there is not much variety to justify the use of "segments" instead of "scene" for one-act plays, and not all characters are speakers).

Also:

* numberOfMaleCharacters → numOfCharactersMale
* numberOfFemaleCharacters → numOfCharactersFemale
* numberOfCharactersWithUnknownGender →numOfCharactersUnknown

**Comment by cmil** [comment]
There are two plays in data.yaml where `created` has the full date including month and day. Fir those `yearWritten` would be kind of a misnomer.

**Comment by lehkost** [comment]
Thanks for spotting these, one was a mistake (_created_ instead of _premiered_), the other one was trimmed to the year information only. Fixed in https://github.com/dracor-org/einakter/commit/1520fd14951d7318fba6308879899e84bc8cb12d.
