### ISSUE TITLE
Enhance startpage statistics

### ISSUE THREAD

**Issue by lehkost** [dracor-org/einakter#65]
The author data we gather from Wikidata should allow for a breakdown into male/female authors. While we're at it, could we maybe enhance the startpage statistics a bit, maybe eventually evolving into some kind of "general statistics" box, something like this:

* Database statistics (as of 10 Sep 2021):
  * One-act plays: 2150
  * Authors: x00 (m: x00, f: x0)
  * Plays published anonymously: x00
  * Plays translated/adapted from other languages: x00 ```(= basedOn)```
  * Characters: 15100 (m: x000, f: x000, u: x00)

**Comment by cmil** [comment]
With the current implementation of the author information for individual plays, where we do a SPARQL query each time the detail view of a play is rendered, we actually don't use `authors.json` anymore. So is the male/ female important enough to keep the information gathering script in place?

**Comment by lehkost** [comment]
This kind of statistics is definitely what we're aiming at, but yes, we'd need to centralise this information to count male/female authors without having to query over and over again.

Is there a downside to storing author data locally in "authors.json" (just updating it when there are new entries just like with locations)? I know we would still load the Wikimedia Commons image from its web source, but the rest would come from our local file…

**Comment by cmil** [comment]
There is no real downside. It just looked like quite some effort and code that need to be maintained for just one detail of information. I was hoping that directly querying Wikidata on an as-needed basis would free us from maintaining our own database of author information. Of course, if the information is valuable enough and important for the project then we can keep it, since the code is already there.

**Comment by lehkost** [comment]
Yes, what a luxury that we already have that code! 🙏 I think it will be advantageous to be able to do a bulk analysis/statistics with all author data even beyond gender. Think life spans, birth/death places (cf. [here](https://dlina.github.io/The-Birth-and-Death-of-German-Playwrights/)), or a gallery (cf. [here](https://dlina.github.io/The-Facebook-of-German-Playwrights/))…

Would it be possible to re-factor the code to read the local json file instead? Although then we would have to update it every time a new author enters the picture…
